# Generated by Django 5.0.7 on 2024-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpost",
            old_name="username",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="userpost",
            name="file",
            field=models.FileField(blank=True, upload_to="upload"),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="text",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
