# Generated by Django 5.0.7 on 2024-08-05 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_userfollowers_usersubscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
