# Generated by Django 5.0.7 on 2024-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_userpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="image",
            field=models.ImageField(blank=True, upload_to="upload/imgs"),
        ),
        migrations.AddField(
            model_name="userpost",
            name="video",
            field=models.FileField(blank=True, upload_to="upload/videos"),
        ),
        migrations.AlterField(
            model_name="userpost",
            name="file",
            field=models.FileField(blank=True, upload_to="upload/files"),
        ),
    ]
