# Generated by Django 5.0.7 on 2024-08-07 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_userpost_image_userpost_video_alter_userpost_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
